<a href="https://colab.research.google.com/github/eildes06/Assigments/blob/main/Assignment_1_Student_(birlikte).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [2]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [3]:
n1=np.ones((4,4), dtype=int)
n1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:
print(np.ones((4,4), dtype=int).reshape)
np.ones

<built-in method reshape of numpy.ndarray object at 0x7f0ea88cadf0>


<function numpy.ones>

In [ ]:
a=np.ones((4,4),dtype=int)
b=np.where(1,7,a)
b

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
a=np.ones((4,4),dtype=int)
b=np.where(1,7,a)
b

#### 6. Create same array above with full method

In [ ]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,17,2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,24,25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.rand(5)

array([0.65549475, 0.46864432, 0.07072703, 0.73790181, 0.40283017])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.rand(5,5)

array([[0.87135442, 0.20562428, 0.34760808, 0.56602898, 0.20895059],
       [0.3665561 , 0.19221963, 0.48049178, 0.09068976, 0.42766543],
       [0.55882314, 0.63648047, 0.14908652, 0.01125046, 0.31359345],
       [0.99776511, 0.32455296, 0.68490705, 0.3007646 , 0.98886055],
       [0.74762362, 0.20717111, 0.92857466, 0.89420305, 0.68361774]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50,size=(3,4))

array([[37, 24, 34, 37],
       [25, 41, 32, 47],
       [34, 46, 24, 33]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
ranarr=[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]

In [ ]:
ranarr =np.array(ranarr)
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [ ]:
np.array(ranarr).reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [ ]:
#reshape with -1
np.array(ranarr).reshape(4,12)

array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [ ]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
mat[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
mat[:,0]

array([ 1,  5,  9, 13])

In [ ]:
mat[:,[0]]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
mat[1,[0,2]]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[:,2] =77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [ ]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
arr2=np.array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
np.std(arr2)

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
sum(mat[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat[:,2]=[3,7,11,15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[2]


array([ 9, 10, 11, 12])

In [ ]:
#median
np.median(mat[2])

10.5

In [ ]:
#mean
np.mean(mat[2])

10.5

In [ ]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [4]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [6]:
sal=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Salaries.csv')

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [ ]:
sal.iloc[-5:]

Id   EmployeeName  ...         Agency  Status
148649  148650  Roy I Tillery  ...  San Francisco     NaN
148650  148651   Not provided  ...  San Francisco     NaN
148651  148652   Not provided  ...  San Francisco     NaN
148652  148653   Not provided  ...  San Francisco     NaN
148653  148654      Joe Lopez  ...  San Francisco     NaN

[5 rows x 13 columns]

In [ ]:
sal.iloc[:5]

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [21]:
"ALBERT PARDINI" in sal

False

In [23]:
"CHRISTOPHER CHONG" in "EmployeeName"

False

In [26]:
"WIRE ROPE CABLE MAINTENANCE MECHANIC" isin "JobTitle"

SyntaxError: ignored

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


TypeError: ignored

In [11]:
sal.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [8]:
sal.isnull()

Id  EmployeeName  JobTitle  BasePay  ...   Year  Notes  Agency  Status
0       False         False     False    False  ...  False   True   False    True
1       False         False     False    False  ...  False   True   False    True
2       False         False     False    False  ...  False   True   False    True
3       False         False     False    False  ...  False   True   False    True
4       False         False     False    False  ...  False   True   False    True
...       ...           ...       ...      ...  ...    ...    ...     ...     ...
148649  False         False     False    False  ...  False   True   False    True
148650  False         False     False     True  ...  False   True   False    True
148651  False         False     False     True  ...  False   True   False    True
148652  False         False     False     True  ...  False   True   False    True
148653  False         False     False    False  ...  False   True   False    True

[148654 rows x 13 columns]

In [ ]:
sal=pd.DataFrame(sal)

In [ ]:
sal.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [ ]:
#max
#sal.TotalPay.max()
max(sal.TotalPay)

567595.43

In [12]:
#avg
sal_avg=sal["TotalPay"].mean()
sal["TotalPay"].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [13]:
(sal.TotalPay>sal_avg).value_counts()

False    79165
True     69489
Name: TotalPay, dtype: int64

In [ ]:
(sal.TotalPay>74768.321971703).value_counts()

False    79165
True     69489
Name: TotalPay, dtype: int64

**How much does ALBERT PARDINI make (including benefits)?**

In [14]:
ALBERT PARDINI  in TotalPayBenefits

SyntaxError: ignored

In [ ]:
sal["TotalPayBenefits"][2]   #İSTEDİĞİMİZ SÜTÜNDAKİ istediğimiz satır

335279.91

**Who is lowest paid person**

In [ ]:
sal["EmployeeName"].iloc[sal.TotalPay.sort_values().head(1)]


148036    Carlos J Hernandez
Name: EmployeeName, dtype: object

In [ ]:
[sal.TotalPay.sort_values(ascending=False).tail(1)]  

[148653   -618.13
 Name: TotalPay, dtype: float64]

In [ ]:
sal.loc[148653 ,"EmployeeName"]

'Joe Lopez'

In [ ]:
sal['TotalPay'].describe()#sadece bir kolona ait veri istiyor ve tanimlatirsin

count    148654.000000
mean      74768.321972
std       50517.005274
min        -618.130000
25%       36168.995000
50%       71426.610000
75%      105839.135000
max      567595.430000
Name: TotalPay, dtype: float64

In [ ]:
sal['TotalPay'].min()

-618.13

In [ ]:
sal[sal["EmployeeName"]== "-618.13"]

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

In [ ]:
sal[sal["EmployeeName"]== "-618.13"]

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

In [ ]:
#sal[(sal["EmployeeName"])][(sal(["TotalPay"]==-618.13))]

KeyError: ignored

In [28]:
sal["JobTitle"].value_counts().sort_values()[0:3]

COURT PARALEGAL     1
METALSMITH          1
MAYORAL STAFF XI    1
Name: JobTitle, dtype: int64

In [27]:
sal.loc[sal["TotalPay"].idxmin()]["EmployeeName"]

'Joe Lopez'

**What are the unique Jobs in dataset?**

In [ ]:
sal.JobTitle.sort_index().unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [ ]:
sal.JobTitle.value_counts()

Transit Operator                                  7036
Special Nurse                                     4389
Registered Nurse                                  3736
Public Svc Aide-Public Works                      2518
Police Officer 3                                  2421
                                                  ... 
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I       1
AREA SUPERVISOR, PARKS, SQUARES AND FACILITIES       1
ASSISTANT DIRECTOR OF CLINICAL SERVICES II           1
Mobile Equipment Supervisor                          1
COURT CLERK                                          1
Name: JobTitle, Length: 2159, dtype: int64

In [ ]:
sal.JobTitle.value_counts(ascending=True).head(3)

COURT CLERK                                   1
Mobile Equipment Supervisor                   1
ASSISTANT DIRECTOR OF CLINICAL SERVICES II    1
Name: JobTitle, dtype: int64

In [ ]:
sal.JobTitle.value_counts().tail(3)

ASSISTANT DIRECTOR OF CLINICAL SERVICES II    1
Mobile Equipment Supervisor                   1
COURT CLERK                                   1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [ ]:
sal["TotalPayBenefits"].mean()

93692.55481056834

In [ ]:
sal.groupby(["Year"]).count()

Id  EmployeeName  JobTitle  ...  Notes  Agency  Status
Year                                 ...                       
2011  36159         36159     36159  ...      0   36159       0
2012  36766         36766     36766  ...      0   36766       0
2013  37606         37606     37606  ...      0   37606       0
2014  38123         38123     38123  ...      0   38123       0

[4 rows x 12 columns]

In [ ]:
sal[(sal["Year"]==2012)&(sal["TotalPayBenefits"]>93692.55481056834)].count()

Id                  20366
EmployeeName        20366
JobTitle            20366
BasePay             20366
OvertimePay         20366
OtherPay            20366
Benefits            20366
TotalPay            20366
TotalPayBenefits    20366
Year                20366
Notes                   0
Agency              20366
Status                  0
dtype: int64

In [37]:
sal[ (sal.TotalPayBenefits>sal.TotalPayBenefits.mean()) & (sal.Year==2012) ].count()

Id                  20366
EmployeeName        20366
JobTitle            20366
BasePay             20366
OvertimePay         20366
OtherPay            20366
Benefits            20366
TotalPay            20366
TotalPayBenefits    20366
Year                20366
Notes                   0
Agency              20366
Status                  0
dtype: int64

In [31]:
len(sal[sal["TotalPayBenefits"]>sal["TotalPayBenefits"].mean()].loc[sal['Year'] == 2012])

20366

In [32]:
sayi = sal[sal['Year']==2012]['TotalPayBenefits']>sal[sal['Year']==2012]['TotalPayBenefits'].mean()         # 2012 de ortalamadan daha fazla kazanan kişi sayısı     
sayi.count()

AttributeError: ignored

In [34]:
sayi = sal[sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean()][sal['Year']==2012]
sayi

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


Id        EmployeeName  ...         Agency  Status
36159  36160      Gary Altenberg  ...  San Francisco     NaN
36160  36161        Gregory Suhr  ...  San Francisco     NaN
36161  36162          Khoa Trinh  ...  San Francisco     NaN
36162  36163  Joanne Hayes-White  ...  San Francisco     NaN
36163  36164   Frederick Binkley  ...  San Francisco     NaN
...      ...                 ...  ...            ...     ...
56520  56521        Sue Madrigal  ...  San Francisco     NaN
56521  56522   Concepcion Gruber  ...  San Francisco     NaN
56522  56523         Kerman Chan  ...  San Francisco     NaN
56523  56524      Ramon Lafuente  ...  San Francisco     NaN
56524  56525      Lai Ping Szeto  ...  San Francisco     NaN

[20366 rows x 13 columns]

In [ ]:
[sal["TotalPayBenefits"]>sal_avg]&()

[0         False
 1         False
 2         False
 3         False
 4         False
           ...  
 148649    False
 148650    False
 148651    False
 148652    False
 148653    False
 Name: TotalPayBenefits, Length: 148654, dtype: bool]

In [ ]:
sal[(sal["TotalPayBenefits"]>sal_avg) &(sal["Year"]==2012)]#and

Id         EmployeeName  ...         Agency  Status
36159  36160       Gary Altenberg  ...  San Francisco     NaN
36160  36161         Gregory Suhr  ...  San Francisco     NaN
36161  36162           Khoa Trinh  ...  San Francisco     NaN
36162  36163   Joanne Hayes-White  ...  San Francisco     NaN
36163  36164    Frederick Binkley  ...  San Francisco     NaN
...      ...                  ...  ...            ...     ...
61420  61421         Taurin Jones  ...  San Francisco     NaN
61421  61422         Jacoby Jones  ...  San Francisco     NaN
61422  61423  Leonora Del Rosario  ...  San Francisco     NaN
61423  61424    Oluwafemi Ekungba  ...  San Francisco     NaN
61424  61425        Edward Harris  ...  San Francisco     NaN

[25266 rows x 13 columns]

**How many people have the word Manager in their job title?**

In [ ]:
#use apply function here
sal[sal["JobTitle"]=="Mobile Equipment Supervisor"]


Id   EmployeeName  ...         Agency  Status
57495  57496  Michael Handy  ...  San Francisco     NaN

[1 rows x 13 columns]

In [ ]:
sal[sal["JobTitle"]=="GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY"]

Id    EmployeeName  ...         Agency  Status
0    1  NATHANIEL FORD  ...  San Francisco     NaN
83  84  EDWARD REISKIN  ...  San Francisco     NaN

[2 rows x 13 columns]

In [ ]:
sal[sal["JobTitle"]=="*MANAGER*"].value_counts()

Series([], dtype: int64)

In [ ]:
sal["JobTitle"].value_counts()

Transit Operator                   7036
Special Nurse                      4389
Registered Nurse                   3736
Public Svc Aide-Public Works       2518
Police Officer 3                   2421
                                   ... 
ASSISTANT RECREATION SUPERVISOR       1
MAYORAL STAFF II                      1
COURT SUPERVISOR I                    1
WAREHOUSE WORKER                      1
Asst Chf Prob Ofc, Juv Prob           1
Name: JobTitle, Length: 2159, dtype: int64

In [38]:
#use apply function here                                   Kaç kişinin iş unvanında Yönetici kelimesi var?
def chief_string(title):
    if 'manager' in title.lower():
        return True
    else:
        return False

sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

4110

In [ ]:
sum(map(chief_string,sal['JobTitle']))

In [ ]:
#df2.groupby("groups").filter(lambda x: x["var2"].sum()<800)

In [40]:
sum(map(chief_string,sal['JobTitle']))

4110

In [39]:
sum(sal['JobTitle'].apply( chief_string))

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [ ]:
sal_new=sal.drop(["BasePay","OvertimePay","OtherPay","Benefits","Year",	"Notes",	"Agency",	"Status"], axis=1)
#sal.drop(columns = ["BasePay","OvertimePay","OtherPay","Benefits","Year",	"Notes",	"Agency",	"Status"])
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [ ]:
sal_new=sal_new.iloc[:,1:]
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

In [41]:
sal_new=sal.iloc[:,[1,2,7,8]]                  # sonra iloc olduğu için indeksleri çağırıyoruz
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

In [45]:
sal_new=sal_new.iloc[:,1:9]
sal_new

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[148654 rows x 0 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [ ]:
sal_new.describe()

Id       TotalPay  TotalPayBenefits
count  148654.000000  148654.000000     148654.000000
mean    74327.500000   74768.321972      93692.554811
std     42912.857795   50517.005274      62793.533483
min         1.000000    -618.130000       -618.130000
25%     37164.250000   36168.995000      44065.650000
50%     74327.500000   71426.610000      92404.090000
75%    111490.750000  105839.135000     132876.450000
max    148654.000000  567595.430000     567595.430000

In [ ]:
sal_new[(sal_new["TotalPay"]>-618.13)&(sal_new["TotalPay"]<74768.32)]

EmployeeName  ... TotalPayBenefits
15847   TATYANA ROTENBERG  ...         74764.87
15848         WINSTON HOM  ...         74761.55
15849        CRAIG RIGLER  ...         74759.92
15850           WENDY TAN  ...         74756.76
15851      KENNETH BREWER  ...         74751.59
...                   ...  ...              ...
148648        Leon Walker  ...             0.00
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00

[79164 rows x 4 columns]

In [ ]:
sal_new[(sal_new["TotalPay"]>-618.13)&(sal_new["TotalPay"]<74768.32)]["EmployeeName"]

15847     TATYANA ROTENBERG
15848           WINSTON HOM
15849          CRAIG RIGLER
15850             WENDY TAN
15851        KENNETH BREWER
                ...        
148648          Leon Walker
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
Name: EmployeeName, Length: 79164, dtype: object

In [46]:
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.min()) & (sal.TotalPayBenefits < sal.TotalPayBenefits.mean())]    # ikinci sorgu şekli kullanılarak çoklu sorgunun yapılması

Id    EmployeeName  ...         Agency  Status
10806    10807         KWE LEE  ...  San Francisco     NaN
10807    10808  MIGUEL CARO JR  ...  San Francisco     NaN
10808    10809   JOANNE MORRIS  ...  San Francisco     NaN
10809    10810   LAYLA WELBORN  ...  San Francisco     NaN
10810    10811         LE BANH  ...  San Francisco     NaN
...        ...             ...  ...            ...     ...
148648  148649     Leon Walker  ...  San Francisco     NaN
148649  148650   Roy I Tillery  ...  San Francisco     NaN
148650  148651    Not provided  ...  San Francisco     NaN
148651  148652    Not provided  ...  San Francisco     NaN
148652  148653    Not provided  ...  San Francisco     NaN

[75649 rows x 13 columns]

In [47]:
sal[(sal["TotalPayBenefits"]>sal["TotalPayBenefits"].min()) & (sal["TotalPayBenefits"]<sal["TotalPayBenefits"].mean())][["EmployeeName"]]

EmployeeName
10806          KWE LEE
10807   MIGUEL CARO JR
10808    JOANNE MORRIS
10809    LAYLA WELBORN
10810          LE BANH
...                ...
148648     Leon Walker
148649   Roy I Tillery
148650    Not provided
148651    Not provided
148652    Not provided

[75649 rows x 1 columns]